//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public List<object> Clientes { get; set; }
        public string ErrorMessage { get; set; }
        public static Cliente NombreClienteGet()
        {
            try
            {
                using (TorneoJRodriguezEntities context = new TorneoJRodriguezEntities())
                {
                    var query = context.NombreClienteGet();
                    if (query != null)
                    {
                        Cliente cliente = new Cliente();
                        cliente.Clientes = new List<object>();
                        foreach (var obj in query)
                        {
                            Cliente cliente1 = new Cliente();
                            cliente1.Nombre = obj;
                            cliente.Clientes.Add(cliente);
                        }
                        return cliente;
                    }
                    else
                    {
                        return new Cliente();
                    }
                }
            }
            catch (Exception e)
            {
                Cliente cliente = new Cliente();
                cliente.ErrorMessage = e.Message;
                return cliente;
            }
        }
    }
}
